field.widget.settings.pretix_date_widget:
  type: mapping
  label: 'Pretix date widget settings'
  mapping:
    spots_min:
      type: integer
      label: 'Spots min'
    spots_max:
      type: integer
      label: 'Spots max'
