#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$script_dir"

execute() {
  classes=(
    'Drupal\itk_pretix\Exporter\CheckInListExporter'
    'Drupal\itk_pretix\Exporter\CheckInListPdfExporter'
    'Drupal\itk_pretix\Exporter\Manager'
    'Drupal\itk_pretix\Exporter\OrderListExporter'
  )
  for class in "${classes[@]}"; do
    compose exec drupal php web/core/scripts/generate-proxy-class.php "$class" "$module_path/src"
  done
}

source "$script_dir/base"
